services:
  maxscale:
    image: wucris/mariadb-maxscale:${MAXSCALE_VERSION}
    container_name: maxscale
    ports:
      - "127.0.0.1:4008:4008"
      - "127.0.0.1:4006:4006"
      - "127.0.0.1:8989:8989"
    build:
      context: .
      args:
      - MAXSCALE_VERSION=${MAXSCALE_VERSION}
    environment:
      SLAVE_HOST:
      SLAVE_PORT:
      MASTER_SERVER:
      MASTER_PORT:
      SLAVE_SERVER:
      MAXSCALE_USER:
      MAXSCALE_PASS:
      MON_INTERVAL:
      LISTENING_PORT:
      MAXSCALE_VERSION: